# Generated by Django 2.1.3 on 2018-11-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=350)),
                ('business_reg_no', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=250)),
                ('owner_id_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Freelancer')),
                ('saloon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Freelancer')),
                ('saloon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelancer.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skill',
            field=models.ManyToManyField(to='freelancer.Skill'),
        ),
    ]
