# Generated by Django 2.1.3 on 2018-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_auto_20181123_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='skill',
            field=models.ManyToManyField(to='freelancer.Skill'),
        ),
    ]
